W-13595824: [SN] add UnionFlattenerStage to avoid nested unions when having 3+ members
aml-org/amf pull request #1812
Opened 2023-06-16 19:41 UTC by arielmirra

2023-06-16 20:34 UTC, nschejtman requested changes

2023-06-16 20:34 UTC, nschejtman commented on amf-cli/shared/src/test/resources/upanddown/raml10/unions/triple-unions.resolved.flattened.jsonld
> +          "@id": "#18"
This anyOf has duplicated IDs

2023-06-22 14:58 UTC, looseale approved these changes

2023-06-22 20:14 UTC, nschejtman approved these changes

2023-06-22 22:00 UTC, merged