APIMF-1961, APIMF-1978, APIMF-1979, APIMF-1980, APIMF-1981: Add Security Scheme warnings
aml-org/amf pull request #325
Opened 2020-06-25 21:59 UTC by arielmirra

if the security scheme is of type "basic", it should not have extra settings fields such as tokenUrl or flow. Only valid fields are description and name.

2020-06-26 01:39 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/parser/spec/declaration/Oas2SecuritySettingsParser.scala
> +      .orElse({ handleNoSettings() })
- [x] Remove parenthesis
- [x] Function name can be more descriptive like something with "validate"

2020-06-26 01:40 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/parser/spec/declaration/Oas2SecuritySettingsParser.scala
> +    if (schemeType == "Basic Authentication" && settingsPresent)
```suggestion
   const BASIC_AUTHENTICATION_SCHEME = "Basic Authentication"
    if (schemeType == BASIC_AUTHENTICATION_SCHEME && settingsPresent)
```
Extract constant to a more significant place

2020-06-26 01:43 UTC, tomsfernandez requested changes

2020-06-26 01:43 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/validations/CustomShaclFunctions.scala
> +    "mandatoryEmptyBasicSecurityScheme" -> ((element, violation) => {
- [x] Erase, no longer needed

2020-06-26 01:43 UTC, tomsfernandez commented on amf-client/shared/src/test/resources/validations/oas2/security/missing-authorizationUrl-oauth2.json
> +{
- [x] Should be removed from commit if it isn't used.

2020-06-27 00:27 UTC, tomsfernandez commented
Talking with @AgustinBettati we thought that it would be worth analyzing if this could be implemented with a closedShape validation.

2020-06-30 16:18 UTC, arielmirra commented on amf-client/shared/src/test/resources/validations/oas2/security/missing-authorizationUrl-oauth2.json
> +{
it's not new, it's from a test that was on Oas30 and I moved it to Oas20 test suite to match its type.

2020-07-24 14:50 UTC, tomsfernandez commented
You should also limit the validations to OAS 2.0 as currently they are running for OAS 2.0 and OAS 3.0. To do this you should subclass the `OasSecuritySchemeParser` into Oas 2 and Oas 3 following convention and only apply the custom Syntax to OAS 2.0 only

2020-07-24 14:50 UTC, tomsfernandez commented
Also to finish this feature you should run some sets just in case we are introducing a new validation that we didn't take into account.

2020-07-28 17:15 UTC, tomsfernandez requested changes

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +          val key: String = entry.key.asScalar.map(_.text).getOrElse(entry.key.toString)
Should be refactored into a function getEntryKey() or something like that

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +          if (ignore(shape, key)) {
shouldn't have empty clause. Should be merged with the clause below

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +            entry.key.asScalar.map(_.text).getOrElse(entry.key.toString)
Should be refactored into a function getEntryKey() or something like that

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +      required.foreach { field =>
Refactor into function

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +        if (!possible.contains(entry) && !required.map(_.name).contains(entry)) {
Possible entries should contain required entries. 
Avoid using `map` method for every entry.

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/parser/spec/declaration/OasSecuritySchemeParser.scala
> +    if (!flow.isEmpty) ctx.closedShape(scheme.id, map, flow)
only one closedShape call should run, not 2. If YAML map does not contain "flow" key then the **fallback** should be "oauth2"

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/parser/spec/declaration/OasSecuritySchemeParser.scala
> +      case Some("basic")  => "basic"
Key to call closedShape should be extracted into a function. Take into account the comment about **oauth2** being a fallback to also include the "flow" choosing

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +      val (required, possible) = (specNode.requiredFields, specNode.possibleFields)
Redundant, not necessary

2020-07-28 17:15 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/contexts/CustomClosedShapeContextDecorator.scala
> +        } else specificClosedShape(node, shape, ast)
specificClosedShape is redundant. Should use throwClosedShapeError

2020-07-30 17:52 UTC, tomsfernandez submitted a review, later dismissed

2020-07-31 14:24 UTC, AgustinBettati approved these changes

2020-07-31 14:51 UTC, merged