APIMF-2563: Metamodel modifications for Json Schema Draft 2019-09
aml-org/amf pull request #683
Opened 2020-10-13 13:53 UTC by tomsfernandez

To be merged after release. Model version is still to be decided

2020-10-14 15:02 UTC, antoniogarrote submitted a review, later dismissed
Would be good to make a pass at SHACL and double-check that there are not matching constraints we could map the new ones to.

2020-10-14 17:31 UTC, tomsfernandez commented
Found the following SHACL mappings:
- DataArrangementModel / Contains -> sh:qualifiedValueShape
- DataArrangementModel / MinContains -> sh:qualifiedMinCount
- DataArrangementModel / MaxContains -> sh:qualifiedMaxCount

2020-10-20 22:59 UTC, antoniogarrote requested changes
Some minor points about missing documentation

2020-10-20 22:59 UTC, antoniogarrote commented on amf-webapi/shared/src/main/scala/amf/plugins/domain/shapes/metamodel/NodeShapeModel.scala
> +    ModelDoc(ModelVocabularies.Shapes, "unevaluatedProperties", /* TODO: Add Something here*/ ""))
Missing documentation

2020-10-20 22:59 UTC, antoniogarrote commented on amf-webapi/shared/src/main/scala/amf/plugins/domain/shapes/metamodel/ArrayShapeModel.scala
> +    ModelDoc(ModelVocabularies.Shapes, "unevaluatedItems", /* TODO: Add Something here*/ ""))
Missing description

2020-10-20 22:59 UTC, antoniogarrote commented on documentation/model.md
> + | unevaluatedItems | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas for th
Wrong description?

2020-10-20 22:59 UTC, antoniogarrote commented on documentation/model.md
> + | unevaluatedItems | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas for th
Wrong description?

2020-10-20 22:59 UTC, antoniogarrote commented on documentation/model.md
> + | unevaluatedProperties | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas f
wrong description?

2020-10-20 22:59 UTC, antoniogarrote commented on documentation/model.md
> + | propertyAppliedShape | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas fo
wrong description?

2020-10-20 22:59 UTC, antoniogarrote commented on documentation/model.md
> + | contentSchema | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas for the d
wrong description?

2020-10-21 17:25 UTC, tomsfernandez commented on documentation/model.md
> + | contentSchema | [Shape](#shape) | Base class for all shapes. Shapes are Domain Entities that define constraints over parts of a data graph. They can be used to define and enforce schemas for the d
fixed model exporter

2020-10-21 17:28 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/domain/shapes/metamodel/ArrayShapeModel.scala
> +    ModelDoc(ModelVocabularies.Shapes, "unevaluatedItems", /* TODO: Add Something here*/ ""))
Filled description

2020-10-21 17:28 UTC, tomsfernandez commented on amf-webapi/shared/src/main/scala/amf/plugins/domain/shapes/metamodel/NodeShapeModel.scala
> +    ModelDoc(ModelVocabularies.Shapes, "unevaluatedProperties", /* TODO: Add Something here*/ ""))
Filled description

2020-10-21 23:52 UTC, antoniogarrote submitted a review, later dismissed
LGTM!

2020-10-22 14:06 UTC, gutee approved these changes

2020-10-22 14:07 UTC, merged